---
title: "Assignment"
output: 
        html_notebook:
                toc: yes
                toc_float: yes
                theme: cosmo
                highlight: tango
                # css: www/css/main.css
---


```{r, echo = FALSE}
# Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

# Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

# When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

```

## Load Data

Let's load the training and test set into a dataframe

```{r}
training <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv")
testing <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv")
```

## How I built the model

```{r}
plot(training$classe)
```

## How I used Cross Validation



## Out of sample error is

